---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: S3SinkConnectorConnector_0
  namespace: confluent
spec:
  name: S3SinkConnectorConnector_0
  class: io.confluent.connect.s3.S3SinkConnector
  configs:
    errors.retry.delay.max.ms: 5
    topics: test-end-to-end
    format.class: io.confluent.connect.s3.format.json.JsonFormat
    flush.size: 1
    s3.bucket.name: kafka-sink-connector-test
    s3.region: us-east-1
    storage.class: io.confluent.connect.s3.storage.S3Storage
    errors.tolerance: all
    errors.deadletterqueue.topic.name: dlq-test-end-to-end
    errors.deadletterqueue.context.headers.enable: true
    errors.deadletterqueue.topic.replication.factor: 3
  restartPolicy:
    type: OnFailure
    maxRetry: 3
  mountedSecrets:
    - secretRef: c3-mds-client
  config:
    principal.service.name: "${file:/mnt/secrets/c3-mds-client/bearer.txt:username}"
    principal.service.password: "${file:/mnt/secrets/c3-mds-client/bearer.txt:password}"
  
