---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: s3sinkconnector.rtpbi
  namespace: confluent
spec:
  connectClusterRef:
    name: connect
    namespace: confluent
  connectRest:
    tls:
      secretRef: rsa-example-cert-2048
    authentication:
      type: bearer
      bearer:
        secretRef: connect-mds-client
  class: io.confluent.connect.s3.S3SinkConnector
  taskMax: 1
  configs:
    errors.retry.delay.max.ms: "5"
    topics: "test-end-to-end"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    flush.size: "1"
    s3.bucket.name: "kafka-sink-connector-test"
    s3.region: "us-east-1"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    errors.tolerance: "all"
    errors.deadletterqueue.topic.name: "dlq-test-end-to-end"
    errors.deadletterqueue.context.headers.enable: "true"
    errors.deadletterqueue.topic.replication.factor: "3"
    principal.service.name: "${file:/vault/secret/controlcenter/bearer.txt:username}"
    principal.service.password: "${file:/vault/secret/controlcenter/bearer.tx:password}"
  restartPolicy:
    type: OnFailure
    maxRetry: 3
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
    name: internal-connect-s3sinkconnector.rtpbi
spec:
    clustersScopeByIds:
      connectClusterId: confluent.connect #<namespace>.<connect_cluster_name>
    principal:
      name: connect
      type: user
    resourcePatterns:
    - name: s3sinkconnector.rtpbi
      patternType: LITERAL
      resourceType: Connector
    role: ResourceOwner
