# - consumer group named `connect_on_vm`
# - topics prefixed with `operator.connect-`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: ksql-1
  namespace: confluent
spec:
  principal:
    name: ksql
    type: user
  resourcePatterns:
  - name: _confluent-ksql-confluent.ksql_
    patternType: PREFIXED
    resourceType: Group
  - name: confluent.ksql_ksql_processing_log
    patternType: PREFIXED
    resourceType: Topic
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: ksql-2
  namespace: confluent
spec:
  principal:
    name: ksql
    type: user
  resourcePatterns:
  - name: kafka-cluster
    patternType: LITERAL
    resourceType: Cluster      
  - name: confluent.ksql_
    patternType: PREFIXED
    resourceType: TransactionalId
  role: DeveloperWrite
