apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2021-10-27T15:09:54Z"
  generateName: ldap-
  labels:
    app: ldap
    controller-revision-hash: ldap-594fc68dd
    statefulset.kubernetes.io/pod-name: ldap-0
  name: ldap-0
  namespace: confluent
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: ldap
    uid: b3d7dfd9-3c80-419e-b8e1-2e2ef06d599c
  resourceVersion: "1744567"
  uid: aacea317-2130-461b-895c-b95a7c5c5043
spec:
  containers:
  - args:
    - --copy-service
    - --loglevel=debug
    env:
    - name: LDAP_TLS_VERIFY_CLIENT
      value: try
    - name: LDAP_TLS_CRT_FILENAME
      value: tls.crt
    - name: LDAP_TLS_KEY_FILENAME
      value: tls.key
    - name: LDAP_TLS_CA_CRT_FILENAME
      value: ca.crt
    - name: LDAP_TLS
      value: "true"
    - name: LDAP_ADMIN_PASSWORD
      value: 5mCrikP42ngPtGbqM8SbBpd#
    - name: LDAP_CONFIG_PASSWORD
      value: PWvvkxSCshxXgexiVcqb7GP#
    - name: LDAP_DOMAIN
      value: rtpbi.com
    - name: LDAP_ORGANISATION
      value: RTP BI Inc.
    - name: LDAP_READONLY_USER
      value: "true"
    - name: LDAP_READONLY_USER_PASSWORD
      value: BMFuXdtxioyCgv0Oe3RhPej#
    - name: LDAP_READONLY_USER_USERNAME
      value: mds
    image: osixia/openldap:1.5.0
    imagePullPolicy: IfNotPresent
    name: ldap
    ports:
    - containerPort: 389
      name: ldap
      protocol: TCP
    - containerPort: 636
      name: ldaps
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /container/service/slapd/assets/certs
      name: sslcerts-volume
    - mountPath: /var/lib/ldap
      name: ldap-data
    - mountPath: /etc/ldap/slapd.d
      name: ldap-config
    - mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
      name: customldif
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bn9md
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: ldap-0
  nodeName: ip-10-208-76-84.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: ldap
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: ldap-data
    persistentVolumeClaim:
      claimName: ldap-data-ldap-0
  - name: ldap-config
    persistentVolumeClaim:
      claimName: ldap-config-ldap-0
  - name: sslcerts-volume
    secret:
      defaultMode: 420
      secretName: ldap-sslcerts
  - configMap:
      defaultMode: 420
      name: ldap-ldifs
    name: customldif
  - name: kube-api-access-bn9md
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-10-27T15:09:55Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-10-27T15:10:13Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-10-27T15:10:13Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-10-27T15:09:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c9bbcdaf420ba6f1f7c08f9d01ba595d5d975da2118d13de228b58b8757d6663
    image: osixia/openldap:1.5.0
    imageID: docker-pullable://osixia/openldap@sha256:18742e9c449c9c1afe129d3f2f3ee15fb34cc43e5f940a20f3399728f41d7c28
    lastState: {}
    name: ldap
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-10-27T15:10:12Z"
  hostIP: 10.208.76.84
  phase: Running
  podIP: 10.208.76.198
  podIPs:
  - ip: 10.208.76.198
  qosClass: BestEffort
  startTime: "2021-10-27T15:09:55Z"
